Repository casual-simulation/casualos, pull requests merged in 2024-07, with the labels that each got.

#499 Add CLI commands for generating and validating server configs
  CHANGELOG.md
  src/aux-common/rpc/GenericRPCInterface.ts
  src/aux-records/ServerConfig.ts
  src/aux-records/index.ts
  src/aux-server/GettingStarted-aws.md
  src/aux-server/GettingStarted-standalone.md
  src/aux-server/aux-backend/server/config.ts
  src/aux-server/aux-backend/shared/ConfigUtils.ts
  src/aux-server/aux-backend/shared/Instrumentation.ts
  src/aux-server/aux-backend/shared/LoadServer.ts
  src/aux-server/aux-backend/shared/ServerBuilder.ts
  src/casualos-cli/README.md
  src/casualos-cli/cli.ts
  src/casualos-cli/schema.ts
Labels: enhancement, area:cli

#500 Fix an issue where the map portal would still open if set to `null` inside `@onInstJoined`
  CHANGELOG.md
  src/aux-server/aux-web/aux-player/PlayerGameView/PlayerGameView.ts
Labels: bug, area:player

#501 Fix hand mesh positioning in XR
  CHANGELOG.md
  src/aux-server/aux-web/aux-player/scene/PlayerPageSimulation3D.ts
  src/aux-server/aux-web/shared/scene/xr/WebXRControllerMesh.ts
Labels: bug, area:player

#502 Fix/making new tag in system portal not auto pin the new tag
  CHANGELOG.md
  src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.ts
Labels: enhancement, area:player

#512 Allow Studios to configure their own Hume API Key and Secret Key
  CHANGELOG.md
  src/aux-common/common/PolicyPermissions.ts
  src/aux-records/AIController.spec.ts
  src/aux-records/AIController.ts
  src/aux-records/AIHumeInterface.ts
  src/aux-records/MemoryStore.ts
  src/aux-records/PolicyController.spec.ts
  src/aux-records/RecordsController.spec.ts
  src/aux-records/RecordsController.ts
  src/aux-records/RecordsServer.spec.ts
  src/aux-records/RecordsServer.ts
  src/aux-records/RecordsStore.ts
  src/aux-records/SubscriptionConfiguration.ts
  src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
  src/aux-runtime/runtime/AuxLibrary.spec.ts
  src/aux-runtime/runtime/AuxLibrary.ts
  src/aux-runtime/runtime/RecordsEvents.ts
  src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
  src/aux-server/aux-backend/prisma/PrismaRecordsStore.ts
  src/aux-server/aux-backend/schemas/auth.prisma
  src/aux-server/aux-backend/schemas/migrations/20240715154333_add_hume_config_to_studio/migration.sql
  src/aux-server/aux-backend/shared/ServerBuilder.ts
  src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.ts
  src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.vue
  src/aux-vm/managers/RecordsManager.spec.ts
  src/aux-vm/managers/RecordsManager.ts
Labels: enhancement, area:backend, area:runtime, area:auth

#513 Update the BIOS Dialog
  CHANGELOG.md
  src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
  src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.ts
  src/aux-server/aux-web/shared/vue-components/AuthUI/AuthUI.vue
  src/aux-vm-browser/managers/AuthCoordinator.ts
  src/aux-vm-browser/managers/AuthEndpointHelper.ts
  src/aux-vm/auth/AuxAuth.ts
Labels: enhancement

#514 Improve labels
  CHANGELOG.md
  docs/docs/components.jsx
  docs/docs/tags/visualization.mdx
  src/aux-common/bots/Bot.ts
  src/aux-common/bots/BotCalculations.ts
  src/aux-common/bots/test/BotCalculationContextTests.ts
  src/aux-server/aux-web/shared/scene/Text3D.ts
  src/aux-server/aux-web/shared/scene/WordBubble3D.ts
  src/aux-server/aux-web/shared/scene/decorators/LabelDecorator.ts
  src/aux-server/aux-web/shared/scene/decorators/WordBubbleDecorator.ts
Labels: enhancement, area:player

#515 Add the ability to respond to right-click and middle-click in listeners
  CHANGELOG.md
  docs/docs/tags/listen.mdx
  src/aux-common/bots/Bot.ts
  src/aux-server/aux-web/aux-player/MenuBot/MenuBot.ts
  src/aux-server/aux-web/aux-player/MenuBot/MenuBot.vue
  src/aux-server/aux-web/aux-player/MenuPortalConfig.ts
  src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerBotClickOperation.ts
  src/aux-server/aux-web/aux-player/interaction/ClickOperation/PlayerEmptyClickOperation.ts
  src/aux-server/aux-web/aux-player/interaction/PlayerInteractionManager.ts
  src/aux-server/aux-web/shared/MonacoHelpers.ts
  src/aux-server/aux-web/shared/interaction/BaseInteractionManager.ts
  src/aux-server/aux-web/shared/interaction/ClickOperation/BaseClickOperation.ts
  src/aux-server/aux-web/shared/interaction/ClickOperation/BaseEmptyClickOperation.ts
  src/aux-server/aux-web/shared/interaction/ClickOperation/ClickOperationUtils.ts
  src/aux-server/aux-web/shared/scene/Input.ts
  src/aux-server/aux-web/shared/vue-components/BotSheet/BotSheet.ts
  src/aux-server/aux-web/shared/vue-components/CodeToolsPortal/CodeToolsPortal.ts
  src/aux-server/aux-web/shared/vue-components/IdePortal/IdePortal.ts
  src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.ts
  src/aux-server/aux-web/shared/vue-components/TagPortal/TagPortalConfig.ts
Labels: enhancement, area:player

#516 Feat/always show the bot system in the recent tags list in the system portal
  CHANGELOG.md
  src/aux-vm-browser/managers/SystemPortalCoordinator.spec.ts
  src/aux-vm-browser/managers/SystemPortalCoordinator.ts
Labels: enhancement, area:player

#518 feat: Always use high-entropy optimized hashes for session keys
  CHANGELOG.md
  src/aux-records/AuthController.spec.ts
  src/aux-records/AuthController.ts
  src/aux-records/InstrumentedHashHelpers.ts
  src/aux-records/RecordsController.spec.ts
  src/aux-records/RecordsController.ts
  src/crypto/HashHelpers.spec.ts
  src/crypto/HashHelpers.ts
  src/crypto/__snapshots__/HashHelpers.spec.ts.snap
Labels: bug, area:backend

#519 Add the `#meshPositioningMode` tag
  CHANGELOG.md
  docs/docs/tags/visualization.mdx
  src/aux-common/bots/Bot.ts
  src/aux-common/bots/BotCalculations.ts
  src/aux-common/bots/test/BotCalculationContextTests.ts
  src/aux-server/aux-web/shared/scene/decorators/BotShapeDecorator.ts
Labels: enhancement, area:player

#521 Add Anthropic AI Chat
  CHANGELOG.md
  pnpm-lock.yaml
  src/aux-records/AnthropicAIChatInterface.ts
  src/aux-records/GoogleAIChatInterface.ts
  src/aux-records/ServerConfig.ts
  src/aux-records/index.ts
  src/aux-records/package.json
  src/aux-server/aux-backend/shared/ServerBuilder.ts
Labels: enhancement, area:backend

#522 Fix line distance rendering when no arrow head is visible
  CHANGELOG.md
  src/aux-server/aux-web/shared/scene/Arrow3D.ts
Labels: bug, area:player

#523 Support Minio for file storage
  CHANGELOG.md
  docker/conf/minio.env
  docker/docker-compose.arm64.v2.env
  docker/docker-compose.arm64.v2.yml
  docker/docker-compose.dev-otel.yml
  docker/docker-compose.dev.yml
  docker/docker-compose.v2.env
  docker/docker-compose.v2.yml
  jest.config.js
  pnpm-lock.yaml
  src/aux-records/FileRecordsStore.ts
  src/aux-records/ServerConfig.ts
  src/aux-server/aux-backend/minio/MinioFileRecordsStore.ts
  src/aux-server/aux-backend/prisma/PrismaFileRecordsLookup.ts
  src/aux-server/aux-backend/server/.dev.env.json
  src/aux-server/aux-backend/shared/LoadServer.ts
  src/aux-server/aux-backend/shared/ServerBuilder.ts
  src/aux-server/package.json
Labels: enhancement, area:backend

#524 Add new Stable Diffusion models
  CHANGELOG.md
  src/aux-records/StabilityAIImageInterface.spec.ts
  src/aux-records/StabilityAIImageInterface.ts
Labels: enhancement, area:backend

#529 Feat/add the ability to enable semantic error highlighting
  CHANGELOG.md
  docs/docs/tags/config-bot.mdx
  src/aux-common/bots/Bot.ts
  src/aux-server/aux-web/shared/MonacoHelpers.ts
Labels: enhancement, area:player

#530 Add the ability to automatically scan files for moderation labels
  .aws/auth.buildspec.yml
  .aws/casualos.buildspec.yml
  CHANGELOG.md
  docker/docker-compose.dev.yml
  jest.config.js
  pnpm-lock.yaml
  src/aux-common/utils.ts
  src/aux-records-aws/RekognitionModerationJobProvider.ts
  src/aux-records-aws/S3FileRecordsStore.ts
  src/aux-records-aws/SimpleEmailServiceAuthMessenger.ts
  src/aux-records-aws/TextItAuthMessenger.ts
  src/aux-records-aws/index.ts
  src/aux-records-aws/package.json
  src/aux-records/MemoryModerationJobProvider.ts
  src/aux-records/MemoryStore.ts
  src/aux-records/ModerationConfiguration.ts
  src/aux-records/ModerationController.spec.ts
  src/aux-records/ModerationController.ts
  src/aux-records/ModerationJobProvider.ts
  src/aux-records/ModerationScanner.ts
  src/aux-records/ModerationStore.ts
  src/aux-records/NotificationMessenger.spec.ts
  src/aux-records/NotificationMessenger.ts
  src/aux-records/RecordsServer.spec.ts
  src/aux-records/RecordsServer.ts
  src/aux-records/ServerConfig.ts
  src/aux-records/__snapshots__/NotificationMessenger.spec.ts.snap
  src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
  src/aux-records/index.ts
  src/aux-server/GettingStarted-aws.md
  src/aux-server/aux-backend/prisma/PrismaModerationStore.ts
  src/aux-server/aux-backend/schemas/auth.prisma
  src/aux-server/aux-backend/schemas/migrations/20240730193538_add_file_moderation/migration.sql
  src/aux-server/aux-backend/schemas/migrations/20240730204234_make_job_id_nullable/migration.sql
  src/aux-server/aux-backend/serverless/aws/src/handlers/Records.ts
  src/aux-server/aux-backend/serverless/aws/src/handlers/S3Batch.ts
  src/aux-server/aux-backend/serverless/aws/template.yml
  src/aux-server/aux-backend/shared/ConfigUtils.ts
  src/aux-server/aux-backend/shared/LoadServer.ts
  src/aux-server/aux-backend/shared/ServerBuilder.ts
  src/aux-server/package.json
Labels: enhancement, area:backend
