Repository casual-simulation/casualos, pull requests merged in 2024-06, with the labels that each got.

#479 Feature/pressing enter while tag is focused in system portal triggers new tag dialog
  CHANGELOG.md
  src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.vue
Labels: enhancement, area:player

#481 Fix/pinned tags should appear above tags list in system portal
  CHANGELOG.md
  src/aux-server/aux-web/shared/vue-components/SystemPortal/SystemPortal.vue
Labels: enhancement, area:player

#485 Add the PRIVO Certification Seal
  CHANGELOG.md
  policies/default/privacy-policy.md
  src/aux-server/aux-web/aux-auth/iframe/AuthHandler.ts
  src/aux-server/aux-web/aux-auth/site/AuthApp/AuthApp.ts
  src/aux-server/aux-web/aux-auth/site/AuthApp/AuthApp.vue
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.css
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.ts
  src/aux-server/aux-web/aux-player/PlayerHome/PlayerHome.vue
  src/aux-server/aux-web/shared/vue-components/EnterAccountInfoDialog/EnterAccountInfoDialog.ts
  src/aux-server/aux-web/shared/vue-components/EnterAccountInfoDialog/EnterAccountInfoDialog.vue
  src/aux-server/aux-web/shared/vue-components/EnterAddressDialog/EnterAddressDialog.ts
  src/aux-server/aux-web/shared/vue-components/EnterAddressDialog/EnterAddressDialog.vue
  src/aux-server/aux-web/shared/vue-components/HasAccountDialog/HasAccountDialog.ts
  src/aux-server/aux-web/shared/vue-components/HasAccountDialog/HasAccountDialog.vue
  src/aux-vm-browser/managers/AuthEndpointHelper.ts
  src/aux-vm/auth/AuxAuth.ts
Labels: enhancement, area:player, area:auth

#486 Add the ability to record and watch Loom videos in CasualOS
  CHANGELOG.md
  pnpm-lock.yaml
  src/aux-common/bots/BotEvents.ts
  src/aux-common/common/PolicyPermissions.ts
  src/aux-records/LoomController.spec.ts
  src/aux-records/LoomController.ts
  src/aux-records/MemoryStore.ts
  src/aux-records/PolicyController.spec.ts
  src/aux-records/PolicyController.ts
  src/aux-records/RecordsController.spec.ts
  src/aux-records/RecordsController.ts
  src/aux-records/RecordsServer.spec.ts
  src/aux-records/RecordsServer.ts
  src/aux-records/RecordsStore.ts
  src/aux-records/SubscriptionConfiguration.ts
  src/aux-records/__snapshots__/RecordsServer.spec.ts.snap
  src/aux-records/index.ts
  src/aux-records/package.json
  src/aux-runtime/runtime/AuxLibrary.spec.ts
  src/aux-runtime/runtime/AuxLibrary.ts
  src/aux-runtime/runtime/AuxLibraryDefinitions.def
  src/aux-runtime/runtime/__snapshots__/AuxRuntime.spec.ts.snap
  src/aux-server/aux-backend/mongo/MongoDBAuthStore.ts
  src/aux-server/aux-backend/prisma/PrismaRecordsStore.ts
  src/aux-server/aux-backend/schemas/auth.prisma
  src/aux-server/aux-backend/schemas/migrations/20240612200024_add_loom/migration.sql
  src/aux-server/aux-backend/shared/ServerBuilder.ts
  src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.ts
  src/aux-server/aux-web/aux-auth/site/AuthStudio/AuthStudio.vue
  src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.css
  src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.ts
  src/aux-server/aux-web/aux-player/PlayerApp/PlayerApp.vue
  src/aux-server/aux-web/aux-player/index.html
  src/aux-server/aux-web/aux-player/player.html
  src/aux-server/package.json
  src/aux-vm-browser/vm/AuxVMImpl.ts
  src/aux-vm/managers/RecordsManager.ts
Labels: enhancement, area:backend, area:runtime, area:player, area:auth

#488 Fix an issue where YJS updates that overwrite a bot may be processed incorrectly
  CHANGELOG.md
  src/aux-common/partitions/RemoteYjsPartition.spec.ts
  src/aux-common/partitions/RemoteYjsPartition.ts
  src/aux-common/partitions/YjsPartition.spec.ts
  src/aux-common/partitions/YjsPartition.ts
  src/aux-common/partitions/test/UpdateCases.ts
Labels: bug, area:runtime
